### PR TITLE
Fix for Sedlex failing to build on 4.03.

### PR DESCRIPTION
**Pull request by neolem**
This pull request fixes the issue of `sedlex` not building on `ocaml 4.03+beta2`. In addition, current sedlex version in opam is also failing due to the same issue 

A sample error we get is as follows,
```
File "ppx_sedlex.ml", line 79, characters 27-36:
Error: This variant expression is expected to have type Parsetree.constant
       The constructor Const_int does not belong to type Parsetree.constant
```
We get a few other errors all related to the `Parsetree.constant` variant being changed in `4.03`. 

`Parsetree.constant` variant has changed in `4.03`. See [Parsetree.constant 4.03](https://github.com/ocaml/ocaml/blob/trunk/parsing/parsetree.mli#L20)

### CODE REVIEW

**Comment by Drup** [comment]
Unfortunatly, we can't merge this like that, it wouldn't compile on 4.02. We should be able to avoid any preprocessing by using ppx_tool's Ast_convenience functions. Could you give it a try ?

**Comment by alainfrisch** [comment]
What's the problem declaring that the previous released version of sedlex requires 4.02 and the next one 4.03?

**Comment by Drup** [comment]
> What's the problem declaring that the previous released version of sedlex requires 4.02 and the next one 4.03?

It's not nice for users and we can avoid it without too much effort ?

**Comment by rgrinberg** [comment]
Please don't dump 4.02.3 support so fast. The transition to 4.03 isn't going to be so smooth for all of us :(

**Comment by neolem** [comment]
hmm ... @Drup ok, sure thing. I will give it a try later but not too hopeful though :). 

If we want to maintain older compilers then perhaps we can use something like `cppo`. This is used by `utop` to likely provide similar support to older compilers. [utop](https://github.com/diml/utop/blob/master/src/lib/uTop_main.cppo.ml#L868). `cppo` route maybe perhaps more easier, manageable. Thoughts???

**Comment by Drup** [comment]
If you need conditional thing, propose them for inclusion in ppx_tools instead.

**Comment by neolem** [comment]
@Drup sorry for the delay. `ppx_tools Ast_convenience` module and helper functions in that module are already updated to use `4.03` version `parsetree` and it seems it doesn't support `4.02` ocaml. So I am not sure if we can provide backwards compatibility without using something like `cppo`. Perhaps @alainfrisch @whitequark can add support for `4.02` parsetree in `ppx_tools`.

**Comment by whitequark** [comment]
There's a 4.02 release of ppx_tools that supports it.

**Comment by neolem** [comment]
Do you mean ppx_tools that supports both 4.02 and 4.03?

**Comment by whitequark** [comment]
There are two different releases for 4.02 and 4.03, but they have compatible API.

**Comment by neolem** [comment]
So, if we use ppx_tools 4.02, is it upwards compatible with 4.03? i.e. since opam works on source level, can we build both sedlex and ppx_tools(4.02) successfully with 4.03 compiler? I am not really familiar with ppx_tools yet ...

**Comment by whitequark** [comment]
No, ppx_tools 4.02 is only compatible with OCaml 4.02, and ppx_tools 4.03 is only compatible with OCaml 4.03. However, they export the same interface (e.g. the Label module).

**Comment by neolem** [comment]
@whitequark, yep, I thought so. I was looking at in particular [ast_convenience](https://github.com/alainfrisch/ppx_tools/blob/f908f407533609478fcdc15adef5c1aae8106e30/ast_convenience.ml). Is there an api/module that abstracts over the changes in `parsetree` from `4.02` to `4.03`? ,i.e. works with `parsetree` from ocaml `4.02` and `4.03` in the same package version.

We are looking at a mechnism to make sedlex build on both 4.02 and 4.03. Perhaps employing a  similar mechanism that [utop](https://github.com/diml/utop/blob/master/src/lib/uTop_main.cppo.ml#L868) implements to provide backwards compaitibilty for ocaml `<= 4.02` while at the same time supporting `4.03`? 

At the moment `sedlex` is refusing to compile on 4.03 due to api changes in `parsetree` from 4.02. what are our options to make sedlex compatible with `4.02` and `4.03` at the same time? Can ppx_tools provide package that supports both 4.02 and 4.03 at the same time? Is this in the works? Or should we go with cppo?

**Comment by whitequark** [comment]
This is not the job of ppx_tools; use cppo.

**Comment by neolem** [comment]
@Drup @alainfrisch It seems we need to use `cppo` if we want to provide backwards compatibility for 4.02 and be compatible with 4.03 in the same package. Thanks to @whitequark for confirming our choices. 
If  `cppo` is not an option then I think the approach suggested by Alain is the best of the options so far.
> ... declaring that the previous released version of sedlex requires 4.02 and the next one 4.03?

**Comment by Drup** [comment]
> Is there an api/module that abstracts over the changes in parsetree from 4.02 to 4.03? ,i.e. works with parsetree from ocaml 4.02 and 4.03 in the same package version.

Yes, ppx_tools.

I feel like you are imposing meaningless weird constraints. Consider the last version of `lwt`, it has no cppo, it has constraint `ppx_tools > 1.0` and it compiles on both 4.02 and 4.03, using a different ppx_tools versions in each case.

**Comment by neolem** [comment]
ah, okay. Just so that I am understanding you correctly, does this mean to  replace all uses of `parsetree` with ppx_tools `ast_convenience` helper functions? Interesting ... I will look into `lwt` more ... Thanks for the pointer.

**Comment by neolem** [comment]
Hi @Drup, 

I have updated the pull request with the required changes based on our discussion. There are 2 other pull requests(both to ppx_tools(version 4.02 and 4.03) that I have had to send in order to support this pull request. 

`ppx_tools` pull requests
[4.03 #41 ](https://github.com/alainfrisch/ppx_tools/pull/41)
[4.02 #40](https://github.com/alainfrisch/ppx_tools/pull/40)

Thanks.

File: src/syntax/ppx_sedlex.ml [hunk 1]
```diff
@@ -76,7 +76,7 @@ let decision_table p =
 
 
 let appfun s l = app (evar s) l
-let pint i = Pat.constant (Const_int i)
+(* let pint i = Pat.constant (Const_int i) *)
```
Comment (Drup) [inline src/syntax/ppx_sedlex.ml]: Just remove it. :)

**Comment by Drup** [comment]
@neolem Nice. I'll merge when things are merged in ppx_tools are merged.

**Comment by neolem** [comment]
@Drup ppx_tools has merged the required changes. This pull request can be merged now. Thanksl.

File: src/syntax/ppx_sedlex.ml [hunk 2]
```diff
@@ -7,6 +7,7 @@ open Parsetree
 open Asttypes
 open Ast_helper
 open Ast_convenience
+open Ast_convenience.Constant
```
Comment (Drup) [inline src/syntax/ppx_sedlex.ml]: Don't use a global open for this please.

**Comment by neolem** [comment]
@Drup Done. Removed the global open.

**Comment by Drup** [comment]
Thanks!

**Comment by whitequark** [comment]
@Drup so, are you going to merge this?

**Comment by whitequark** [comment]
Actually, looks like it fails to build on 4.03 over here:
```
# File "ppx_sedlex.ml", line 308, characters 60-80:
# Error: Unbound module Constant
# Hint: Did you mean Const?
```

**Comment by alainfrisch** [comment]
> Actually, looks like it fails to build on 4.03 over here:

You should use ppx_tools >= 5.0.

I've pushed the suggest fix (slightly adapted).
